#!/usr/bin/env bash
# Runs the two ROS2 rover programs: subsystems and video.
#
# Usage:
#   ./run_rover.sh          # start both programs
#   ./run_rover.sh stop     # stop both programs
#   ./run_rover.sh status   # show what's running
#   ./run_rover.sh restart  # stop then start
#
# Portability:
# - Works from any directory and with any colcon workspace name/location.
#   Workspace resolution order: $ROVER_WS, then the directory containing this
#   script (if it has install/setup.bash), then ~/rover_ws, then the first
#   ~/..._ws with install/setup.bash.
# - Uses whatever ROS2 distro is installed (first one found under /opt/ros).

# Note: deliberately no `set -u` -- the ROS setup scripts reference unbound variables.
set -o pipefail

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Locate a ROS2 installation (e.g. /opt/ros/humble). Uses the newest distro
# found, or honors $ROS_DISTRO if it is already set.
# ---------------------------------------------------------------------------
find_ros_distro() {
  if [[ -n "$ROS_DISTRO" && -f "/opt/ros/$ROS_DISTRO/setup.bash" ]]; then
    echo "/opt/ros/$ROS_DISTRO"
    return 0
  fi
  local dir distro
  for dir in /opt/ros/*/; do
    [[ -f "$dir/setup.bash" ]] || continue
    distro="$(basename "$dir")"
  done
  if [[ -n "$distro" ]]; then
    echo "/opt/ros/$distro"
  fi
}

# ---------------------------------------------------------------------------
# Locate the colcon workspace containing subsystems_ros2 / video_ros2.
# ---------------------------------------------------------------------------
find_workspace() {
  local candidate
  # 1. Explicit override.
  if [[ -n "$ROVER_WS" && -f "$ROVER_WS/install/setup.bash" ]]; then
    echo "$ROVER_WS"
    return 0
  fi
  # 2. The directory holding this script (if the script lives in a workspace).
  if [[ -f "$SELF/install/setup.bash" ]]; then
    echo "$SELF"
    return 0
  fi
  # 3. Conventional default.
  if [[ -f "$HOME/rover_ws/install/setup.bash" ]]; then
    echo "$HOME/rover_ws"
    return 0
  fi
  # 4. Any ~/..._ws that has been built with colcon.
  for candidate in "$HOME"/*_ws; do
    [[ -f "$candidate/install/setup.bash" ]] || continue
    echo "$candidate"
    return 0
  done
  return 1
}

ROS_DIR="$(find_ros_distro)"
WORKSPACE="$(find_workspace)"

if [[ -z "$ROS_DIR" ]]; then
  echo "error: no ROS2 installation found under /opt/ros" >&2
  exit 1
fi
if [[ -z "$WORKSPACE" ]]; then
  echo "error: could not find a colcon workspace with install/setup.bash." >&2
  echo "       Build one (colcon build) or set ROVER_WS=/path/to/workspace." >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ROS_DIR/setup.bash"
# shellcheck disable=SC1090
source "$WORKSPACE/install/setup.bash"

LOG_DIR="$WORKSPACE/logs"
mkdir -p "$LOG_DIR"

NODES="udp_bridge firmware_manager gps_node imu_node subsystems_node video_node"

# The Dart versions of the same programs run as systemd services named <name>.service
# (executables at $HOME/<name>, generated by `dart run :rover` in Rover-Code), and can
# also be launched manually. Stop all of these before running the ROS2 versions so the
# two implementations never fight over the same UDP ports.
DART_SERVICES="subsystems video"
DART_PATTERN="$HOME/(subsystems|video)( |$)"
DART_RUN_PATTERN='dart .*(bin/)?(subsystems|video)\.dart'

# Match nodes by full command line: process names are truncated to 15 chars by the
# kernel, so `pkill -x firmware_manager` would never match. Pinning to the workspace
# install path (install/<pkg>/lib/<pkg>/<node>) also avoids killing unrelated
# processes that happen to share a node name. $WORKSPACE is escaped so that paths
# with special regex characters (or symlinks like /root) still match correctly.
NODE_PATTERN="$(printf '%s' "$WORKSPACE" | sed 's/[][\.*^$()+?{}|]/\\&/g')/install/[^/]+/lib/[^/]+/"

is_running() {
  pgrep -f "$NODE_PATTERN$1( |$)" > /dev/null
}

start_programs() {
  # Stop leftovers first so ports 8001/8002 are free.
  stop_programs

  echo "Starting subsystems (ports 8001 + 8002)..."
  setsid nohup ros2 launch subsystems_ros2 subsystems.launch.py \
    > "$LOG_DIR/subsystems.log" 2>&1 < /dev/null &
  disown

  echo "Starting video (all virtual test cameras)..."
  setsid nohup ros2 launch video_ros2 video.launch.py \
    > "$LOG_DIR/video.log" 2>&1 < /dev/null &
  disown

  sleep 5
  status_programs
  echo "Logs: $LOG_DIR/subsystems.log, $LOG_DIR/video.log"
}

stop_programs() {
  pkill -f "$NODE_PATTERN" 2> /dev/null
  pkill -x ros2 2> /dev/null

  # Stop the Dart versions: the systemd services first, then any manually
  # launched executables or `dart run` instances.
  if command -v systemctl > /dev/null; then
    for service in $DART_SERVICES; do
      systemctl is-active --quiet "$service" 2> /dev/null || continue
      echo "Stopping dart service: $service.service"
      sudo systemctl stop "$service.service" || echo "  warning: could not stop $service.service (sudo denied?)"
    done
  fi
  pkill -f "$DART_PATTERN" 2> /dev/null
  pkill -f "$DART_RUN_PATTERN" 2> /dev/null
  sleep 2
}

status_programs() {
  local any=0
  for node in $NODES; do
    if is_running "$node"; then
      echo "  [running] $node"
      any=1
    fi
  done
  for service in $DART_SERVICES; do
    if systemctl is-active --quiet "$service" 2> /dev/null; then
      echo "  [running] dart $service.service"
      any=1
    fi
  done
  if [[ $any -eq 0 ]]; then
    echo "  no rover programs are running"
  fi
}

case "${1:-start}" in
  start)   start_programs ;;
  stop)    stop_programs;  status_programs ;;
  status)  status_programs ;;
  restart) stop_programs;  start_programs ;;
  *)
    echo "Usage: $0 [start|stop|status|restart]"
    exit 1
    ;;
esac
