export "generated/arm.pb.dart";
export "generated/autonomy.pb.dart";
export "generated/core.pb.dart";
export "generated/drive.pb.dart";
export "generated/electrical.pb.dart";
export "generated/gps.pb.dart";
export "generated/mars.pb.dart";
export "generated/science.pb.dart";
export "generated/video.pb.dart";
export "generated/wrapper.pb.dart";
export "generated/google/protobuf/timestamp.pb.dart";

import "package:protobuf/protobuf.dart" as proto;

import "generated/wrapper.pb.dart";
import "generated/google/protobuf/timestamp.pb.dart";

/// A cleaner name for any message generated by Protobuf.
typedef Message = proto.GeneratedMessage;

/// Defines a friendlier method for getting the name of a message.
extension MessageUtils on Message {
	/// The name of the message as declared in the .proto file. 
	String get messageName => info_.messageName;

	/// Returns a [WrappedMessage] representing this message with a timestamp
	WrappedMessage wrap([DateTime? timestamp]) => WrappedMessage(
		data: writeToBuffer(),
		name: messageName,
		timestamp: Timestamp.fromDateTime(timestamp ?? DateTime.now()),
	);
}
