name: subsystems
description: A sample command-line application.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  burt_network: ^2.7.0
  collection: ^1.19.0
  csv: ^6.0.0
  dart_dbc_generator:
    git: https://github.com/Gold872/dart_dbc_generator.git
  ffi: ^2.1.3
  linux_can: ^0.2.0
  osc: ^1.0.0

dev_dependencies:
  ffigen: ^19.1.0
